### ISSUE TITLE
Animation flickering with pagination

### ISSUE THREAD

**Issue by jscontrust** [michaelbromley/angularUtils#226]
I have a flickering problem with combining angularUtils pagination with ngAnimate (Angular 1.4)

I recorded a screen video from it
http://www.vidup.de/v/oHhCU/

It looks like all of the records are in the array for a short time:

Is there a fix or workaround?

My CSS

    .animate-repeat-tablerow.ng-move,
    .animate-repeat-tablerow.ng-enter,
    .animate-repeat-tablerow.ng-leave {
        transition:all linear 0.2s;
    }

    .animate-repeat-tablerow.ng-leave.ng-leave-active,
    .animate-repeat-tablerow.ng-move,
    .animate-repeat-tablerow.ng-enter {
        opacity:0;
    }

    .animate-repeat-tablerow.ng-leave,
    .animate-repeat-tablerow.ng-move.ng-move-active,
    .animate-repeat-tablerow.ng-enter.ng-enter-active {
        opacity:1;
    }

My HTML:
```html
    <table>
        <tr dir-paginate='download in downloads | filter: filterDownloads | itemsPerPage: 2 ' class="animate-repeat-tablerow">
            <td>
                {{download.post_title}}
                <p class='font_size_small no_margin'>{{download.download_description}}</p>
            </td>
            <td>
                <span ng-repeat='term in download.terms'>{{term.name}}</span>
            </td>
            <td>                    
                <span ng-repeat='relation in download.download_relations | filter: { "post_type":"product-group" }'>{{relation.post_title}}</span>
            </td>                                   
        </tr>
    </table>    
```

**Comment by vapits** [comment]
Could you provide a jsfidlle or something working?

**Comment by michaelbromley** [comment]
Hi,

I'm aware of this issue, but right now there is no simple fix, other than getting creative with your CSS skills.

For example, if the "leaving" animation is instant (zero duration), then this can solve it.

Please take a look at [this answer](https://github.com/michaelbromley/angularUtils/issues/195#issuecomment-122203845) for a slightly more advanced way of getting around it.

**Comment by LeleDev** [comment]
+1

**Comment by fferraris** [comment]
:+1:

**Comment by michaelbromley** [comment]
@jscontrust I know it's been a long time, so maybe you fixed this already, but how about this:

```css
.animate-repeat-tablerow.ng-move,
.animate-repeat-tablerow.ng-enter {
    transition:all linear 0.2s;
}

.animate-repeat-tablerow.ng-leave.ng-leave-active,
.animate-repeat-tablerow.ng-move,
.animate-repeat-tablerow.ng-enter {
    opacity:0;
}

.animate-repeat-tablerow.ng-leave,
.animate-repeat-tablerow.ng-move.ng-move-active,
.animate-repeat-tablerow.ng-enter.ng-enter-active {
    opacity:1;
}

.animate-repeat-tablerow.ng-leave,
.animate-repeat-tablerow.ng-leave.ng-move-active {
  transition: all 0s;
}
```

Plunker: http://plnkr.co/edit/bEvCOVnyKMascsSQzxJD?p=preview

The basic idea is to make sure the outgoing animation (ng.leave -> ng.leave-active) has a zero duration. This allows it to get out of the way before the next page fades in.

Other "plus one" people - does this approach help in your case?
